# config/packages/fos_user.yaml
fos_user:
  registration:
    form:
      type: App\Form\RegistrationType
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "covid19egypt.org@gmail.com"
    sender_name: "Covid-19 Egypt"
#  service:
#    mailer: fos_user.mailer.twig_swift