# src/Acme/UserBundle/Resources/config/services.yml
services:
  app_user.registration_completed:
    class: App\EventListener\RegisterationSuccessListener
    arguments: ['@router', "@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_subscriber }

  app_user.registration_confirmed:
    class: App\EventListener\RegisterationConfirmedListener
    arguments: ['@router']
    tags:
      - { name: kernel.event_subscriber }

  app_user.login_success_handler:
    class:  App\Handler\LoginSuccessHandler
    arguments:  ['@router', '@security.helper']

  App\Doctrine\CasesEntityListener:
    tags:
      - name: 'doctrine.event_listener'
        # this is the only required option for the lifecycle listener tag
        event: 'prePersist'

        # listeners can define their priority in case multiple listeners are associated
        # to the same event (default priority = 0; higher numbers = listener is run earlier)
        priority: 500

        # you can also restrict listeners to a specific Doctrine connection
        connection: 'default'
    arguments:
      ["@doctrine.orm.entity_manager"]

  App\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
    arguments:
      ["@logger", "@doctrine.orm.entity_manager"]

  App\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, , event: kernel.request }
    arguments:
      ["@doctrine.orm.entity_manager", "@twig"]