monolog:
    handlers:
        main:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
#            action_level: critical
            # to also log 400 level errors (but not 404's):
            action_level: error
            # excluded_404s:
            #     - ^/
            handler:      grouped
        grouped:
            type:    group
            members: [streamed]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug